name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install MarkBind
        run: npm install -g markbind-cli
        
      - name: Build site
        run: markbind build
        
      - name: Configure Git
        run: |
          git config --global user.name "Zikun Zhu"
          git config --global user.email "zhu.zikun@u.nus.edu"
        
      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          markbind deploy -n
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 